modified:   README 	modified:   config

diff --git a/config b/config
--- a/config
+++ b/config
@@ -1,14 +1,19 @@
 #!/bin/bash
 
-# ------------
-# Read in the settings for this unit
-# ------------
-source "${0%/*}/config-settings"
-
 # Common logging function
 function log {
   echo "$(date) : $1"
 }
+
+# ------------
+# Read in the settings for this unit
+# ------------
+source "${0%/*}/config-settings"
+if [[ -z "$room" ]]; then
+ log "Cannot start.  Run setup to configure."
+ exit 1
+fi
+
 
 # ------------
 # Common  for all scripts
